services:
  pi-grow-client:
    build: .
    container_name: pi-grow-client
    restart: unless-stopped
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true
    volumes:
      - /sys:/sys
      - /dev:/dev
