services:
  pi-grow-client:
    image: 192.168.1.100:5001/pi-grow-client:latest
    container_name: pi-grow-client
    restart: unless-stopped
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true
    volumes:
      - /sys:/sys
      - /dev:/dev
